### ISSUE TITLE
Probably there is a mistake?

### ISSUE THREAD

**Issue by yesworld** [m-nathani/BitPoint#6]
"DATABASE_URL=mysql://user:password@**localhost**:3306/db_name" instead of

https://github.com/m-nathani/node-typescript-starter/blob/909dffc166dfde5228211c87f9b747cf76b4a437/.env.sample#L10

**Comment by m-nathani** [comment]
hi @yesworld, it could be any of the two, depending where your mysql is hosted.. If you are running through docker then `@mysql:3306` would work w.r.t to mysql container name.. if running directly on the localhost then `@localhost:3306` would work. So that's why i have created a sample file for `.env`, you can change it a/c to your needs.

**Comment by yesworld** [comment]
Thanks for the answer. I created a .env file which I need. I just don't use the docker, that's why I got an error on run.
